import fs from 'node:fs';
import path from 'node:path';
import { CLAUDE } from './paths.js';

// The one thing the board writes.
//
// Session titles are generated by Claude Code into the transcript, which is an
// append-only log the board has no business editing. So a rename is stored as an
// override in a file the board owns, and the transcript is left exactly as it is.
// Clearing the override restores the generated title rather than leaving a blank.

const DIR = path.join(CLAUDE, '.board');
const FILE = path.join(DIR, 'titles.json');

export function readTitles(): Record<string, string> {
  try {
    const parsed = JSON.parse(fs.readFileSync(FILE, 'utf8'));
    return parsed && typeof parsed === 'object' ? (parsed as Record<string, string>) : {};
  } catch {
    return {};
  }
}

/** An empty or whitespace-only title clears the override. Returns the stored value. */
export function setTitle(sessionId: string, title: string): string | null {
  const titles = readTitles();
  const trimmed = title.trim().slice(0, 200);

  if (trimmed) titles[sessionId] = trimmed;
  else delete titles[sessionId];

  fs.mkdirSync(DIR, { recursive: true });
  // Write to a sibling then rename: a torn write here would lose every rename on
  // the machine, and rename is atomic on both platforms this runs on.
  const tmp = `${FILE}.${process.pid}.tmp`;
  fs.writeFileSync(tmp, `${JSON.stringify(titles, null, 2)}\n`);
  fs.renameSync(tmp, FILE);

  return trimmed || null;
}
