export const HEAD_START = '<!-- icons:start — generated by @tickets/icon-studio, do not edit -->';
export const HEAD_END = '<!-- icons:end -->';

/** The two colours the head block needs, already resolved from the document. */
export interface HeadColors {
  /** `rel="mask-icon"`'s colour — the light-theme ink of the leading element. */
  maskIconColor: string;
  /** The chip field colour, shared by the manifest's theme colour. */
  themeColor: string;
}

/**
 * The iOS meta tags are not redundant with the manifest: Safari ignores the
 * manifest when launching from the home screen, so standalone display and the
 * status bar style have to be declared here too.
 *
 * Takes the two resolved colours directly, not a document — like
 * `buildManifest`, this has no notion of elements or inks of its own.
 */
export function buildHeadBlock({ maskIconColor, themeColor }: HeadColors): string {
  return `    ${HEAD_START}
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    <link rel="mask-icon" href="/icon-mono.svg" color="${maskIconColor}" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="manifest" href="/site.webmanifest" />
    <meta name="theme-color" content="${themeColor}" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    ${HEAD_END}`;
}

/**
 * Replaces the marked region, or inserts it before `</head>` the first time.
 * index.html is hand-maintained, so nothing outside the markers is touched and
 * re-running with an unchanged config is a no-op.
 */
export function injectHeadBlock(html: string, block: string): string {
  const start = html.indexOf(HEAD_START);
  const end = html.indexOf(HEAD_END);

  // Guard against malformed marker pairings.
  if ((start === -1) !== (end === -1)) {
    // Exactly one marker is present.
    const missing = start === -1 ? 'HEAD_START' : 'HEAD_END';
    throw new Error(
      `cannot inject icon tags: ${missing} marker missing in index.html. The file requires manual attention to resolve the stale marker.`,
    );
  }

  if (start !== -1 && end !== -1 && end < start) {
    throw new Error(
      'cannot inject icon tags: markers are out of order in index.html. The file requires manual attention to resolve the reversed markers.',
    );
  }

  if (start !== -1 && end !== -1) {
    // Replace path: strip whitespace before marker to avoid double indentation,
    // since buildHeadBlock now owns the indentation for all lines.
    const lineStart = html.lastIndexOf('\n', start) + 1;
    return html.slice(0, lineStart) + block + html.slice(end + HEAD_END.length);
  }

  const close = html.indexOf('</head>');
  if (close === -1) {
    throw new Error('cannot inject icon tags: no </head> found in index.html');
  }

  // Insert path: place block on its own line before </head>.
  // buildHeadBlock owns the indentation for all lines.
  const lineStart = html.lastIndexOf('\n', close) + 1;
  return html.slice(0, lineStart) + block + '\n' + html.slice(lineStart);
}
