import type { MarkConfig } from '../config';

export const HEAD_START = '<!-- icons:start — generated by @tickets/icon-studio, do not edit -->';
export const HEAD_END = '<!-- icons:end -->';

/**
 * The iOS meta tags are not redundant with the manifest: Safari ignores the
 * manifest when launching from the home screen, so standalone display and the
 * status bar style have to be declared here too.
 */
export function buildHeadBlock(c: MarkConfig): string {
  return `${HEAD_START}
    <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
    <link rel="mask-icon" href="/icon-mono.svg" color="${c.light[0]}" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="manifest" href="/site.webmanifest" />
    <meta name="theme-color" content="${c.chip}" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    ${HEAD_END}`;
}

/**
 * Replaces the marked region, or inserts it before `</head>` the first time.
 * index.html is hand-maintained, so nothing outside the markers is touched and
 * re-running with an unchanged config is a no-op.
 */
export function injectHeadBlock(html: string, block: string): string {
  const start = html.indexOf(HEAD_START);
  const end = html.indexOf(HEAD_END);

  // Guard against malformed marker pairings.
  if ((start === -1) !== (end === -1)) {
    // Exactly one marker is present.
    const missing = start === -1 ? 'HEAD_START' : 'HEAD_END';
    throw new Error(
      `cannot inject icon tags: ${missing} marker missing in index.html. The file requires manual attention to resolve the stale marker.`,
    );
  }

  if (start !== -1 && end !== -1 && end < start) {
    throw new Error(
      'cannot inject icon tags: markers are out of order in index.html. The file requires manual attention to resolve the reversed markers.',
    );
  }

  if (start !== -1 && end !== -1) {
    return html.slice(0, start) + block + html.slice(end + HEAD_END.length);
  }

  const close = html.indexOf('</head>');
  if (close === -1) {
    throw new Error('cannot inject icon tags: no </head> found in index.html');
  }

  // Keep the closing tag's own indentation by inserting on the line above it.
  const lineStart = html.lastIndexOf('\n', close) + 1;
  const indent = html.slice(lineStart, close);
  return html.slice(0, lineStart) + indent + block + '\n' + html.slice(lineStart);
}
