import { CENTRE, GRID, type Element, type IconDoc, type InkResolution } from '../doc';

/**
 * One renderer for every variant. `svgFavicon`, `svgBare`, `svgMono` and
 * `svgChip` were four functions drawing the same three sticks differently;
 * with the drawing in the document, they collapse to this.
 *
 * Output format is matched character for character to the generators it
 * replaces, because the committed assets must come out byte-identical.
 */

const BLACK = '#000';

/** Marks the files this module writes straight to disk as generated, not hand-authored. */
const GENERATED_COMMENT = '<!-- generated by @tickets/icon-studio — do not edit -->';

/** A pair of resolved colours. Both are equal for every resolution but `theme`. */
export interface Resolved {
  light: string;
  dark: string;
}

export function resolveInk(doc: IconDoc, name: string, resolution: InkResolution): Resolved {
  if (resolution === 'black') return { light: BLACK, dark: BLACK };
  // A missing ink renders black rather than throwing: a half-edited document
  // should still draw something you can see and fix.
  const ink = doc.inks[name] ?? { light: BLACK, dark: BLACK };
  switch (resolution) {
    case 'light':
      return { light: ink.light, dark: ink.light };
    case 'dark':
      return { light: ink.dark, dark: ink.dark };
    case 'theme':
      return { light: ink.light, dark: ink.dark };
  }
}

/**
 * Trims trailing zeros so `4.6670000000000003` never reaches a committed
 * file. Rounds to 10 decimal places rather than 6 — a repeating scale like
 * `14/18` needs that much headroom before weight/reach's ratio drifts
 * measurably from the value it was derived from.
 */
function num(value: number): string {
  return String(Math.round(value * 1e10) / 1e10);
}

function paintOf(element: Element, className: string | null, colour: string): string {
  return className === null ? ` ${element.type === 'dot' ? 'fill' : 'stroke'}="${colour}"` : ` class="${className}"`;
}

function drawElement(element: Element, scale: number, paint: string): string {
  switch (element.type) {
    case 'stick': {
      const reach = element.reach * scale;
      return (
        `\n    <path d="M${num(CENTRE)} ${num(CENTRE - reach)}L${num(CENTRE)} ${num(CENTRE + reach)}"${paint}` +
        ` stroke-width="${num(element.weight * scale)}" stroke-linecap="round" fill="none"` +
        ` transform="rotate(${num(element.angle)} ${num(CENTRE)} ${num(CENTRE)})"/>`
      );
    }
    case 'ring':
      return (
        `\n    <circle cx="${num(CENTRE)}" cy="${num(CENTRE)}" r="${num(element.radius * scale)}"${paint}` +
        ` stroke-width="${num(element.weight * scale)}" fill="none"/>`
      );
    case 'dot': {
      const [x, y] = element.at;
      // Scale about the centre so a dot keeps its place in the drawing.
      const cx = CENTRE + (x - CENTRE) * scale;
      const cy = CENTRE + (y - CENTRE) * scale;
      return `\n    <circle cx="${num(cx)}" cy="${num(cy)}" r="${num(element.radius * scale)}"${paint}/>`;
    }
  }
}

export function renderSvg(doc: IconDoc, variantName: string): string {
  const variant = doc.variants[variantName];
  if (!variant) throw new Error(`unknown variant "${variantName}"`);
  const { scale, inks: resolution, field } = variant;

  const open = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${GRID} ${GRID}" width="${GRID}" height="${GRID}">`;
  // `favicon` and `mono` are the two variants written straight to a committed
  // asset (see `generate/svg.ts`'s old `svgFavicon`/`svgMono`); `chip` and any
  // single-theme variant are consumed elsewhere and were never marked.
  const comment =
    resolution === 'theme' || resolution === 'black' ? `\n  ${GENERATED_COMMENT}` : '';
  const plate = field
    ? `\n  <rect width="${GRID}" height="${GRID}" rx="${num(field.radius)}" fill="${
        resolveInk(doc, field.ink, resolution === 'theme' ? 'dark' : resolution).light
      }"/>`
    : '';

  if (resolution === 'theme') {
    // A favicon has no inherited colour, so both sets are inlined and swapped
    // by a media query inside the file itself.
    const rules = doc.elements
      .map((element, i) => {
        const { light } = resolveInk(doc, element.ink, 'light');
        return `.e${i}{${element.type === 'dot' ? 'fill' : 'stroke'}:${light}}`;
      })
      .join('');
    const darkRules = doc.elements
      .map((element, i) => {
        const { dark } = resolveInk(doc, element.ink, 'theme');
        return `.e${i}{${element.type === 'dot' ? 'fill' : 'stroke'}:${dark}}`;
      })
      .join('');
    const body = doc.elements
      .map((element, i) => drawElement(element, scale, paintOf(element, `e${i}`, '')))
      .join('');
    return `${open}${comment}${plate}
  <style>
    ${rules}
    @media (prefers-color-scheme:dark){${darkRules}}
  </style>
  <g fill="none">${body}
  </g>
</svg>
`;
  }

  const body = doc.elements
    .map((element) =>
      drawElement(element, scale, paintOf(element, null, resolveInk(doc, element.ink, resolution).light)),
    )
    .join('');
  return `${open}${comment}${plate}
  <g fill="none">${body}
  </g>
</svg>
`;
}

/** How far the drawing reaches from the centre, including any stroke cap. */
export function outerExtent(doc: IconDoc, variantName: string): number {
  const variant = doc.variants[variantName];
  if (!variant) throw new Error(`unknown variant "${variantName}"`);
  const reaches = doc.elements.map((element) => {
    switch (element.type) {
      case 'stick':
        return element.reach + element.weight / 2;
      case 'ring':
        return element.radius + element.weight / 2;
      case 'dot': {
        const [x, y] = element.at;
        return Math.hypot(x - CENTRE, y - CENTRE) + element.radius;
      }
    }
  });
  return Math.max(0, ...reaches) * variant.scale;
}

/** That extent as a percentage of the tile's half-width. Android crops at 80. */
export function safeZonePct(doc: IconDoc, variantName: string): number {
  return (outerExtent(doc, variantName) / CENTRE) * 100;
}
