// GENERATED by scripts/build-tokens.mjs from src/tokens/next/tones.tokens.json — do not edit.
// Literal class strings so Tailwind can scan them; see build-tokens.mjs emitTones().
export const TONE_NAMES = ['primary', 'secondary', 'success', 'warning', 'danger', 'neutral', 'red', 'orange', 'yellow', 'green', 'teal', 'cyan', 'blue', 'indigo', 'purple', 'pink', 'gray'] as const;
export type Tone = (typeof TONE_NAMES)[number];
export const ROLE_TONES = ['primary', 'secondary', 'success', 'warning', 'danger', 'neutral'] as const;
export type RoleTone = (typeof ROLE_TONES)[number];
export const HUE_TONES = ['red', 'orange', 'yellow', 'green', 'teal', 'cyan', 'blue', 'indigo', 'purple', 'pink', 'gray'] as const;
export type HueTone = (typeof HUE_TONES)[number];
export type ToneEmphasis = 'subtle' | 'solid' | 'outline' | 'text';
export const TONE_SCALE: Record<Tone, HueTone> = {
  'primary': 'indigo',
  'secondary': 'gray',
  'success': 'green',
  'warning': 'orange',
  'danger': 'red',
  'neutral': 'gray',
  'red': 'red',
  'orange': 'orange',
  'yellow': 'yellow',
  'green': 'green',
  'teal': 'teal',
  'cyan': 'cyan',
  'blue': 'blue',
  'indigo': 'indigo',
  'purple': 'purple',
  'pink': 'pink',
  'gray': 'gray',
};
export const STEP = {
  bgSubtle: 3,
  bgSubtleHover: 4,
  bgSubtleActive: 5,
  border: 7,
  borderHover: 8,
  solid: 9,
  solidHover: 10,
  solidActive: 11,
  text: 11,
  textStrong: 12,
  contrast: 'contrast',
  focusRing: 3,
} as const;
export const TONES: Record<Tone, Record<ToneEmphasis, string>> = {
  'primary': {
    subtle: 'bg-indigo-3 text-indigo-11',
    solid: 'bg-indigo-9 text-indigo-contrast',
    outline: 'border-(length:--border-thick) border-indigo-7 text-indigo-11',
    text: 'text-indigo-11',
  },
  'secondary': {
    subtle: 'bg-gray-3 text-gray-11',
    solid: 'bg-gray-9 text-gray-contrast',
    outline: 'border-(length:--border-thick) border-gray-7 text-gray-11',
    text: 'text-gray-11',
  },
  'success': {
    subtle: 'bg-green-3 text-green-11',
    solid: 'bg-green-9 text-green-contrast',
    outline: 'border-(length:--border-thick) border-green-7 text-green-11',
    text: 'text-green-11',
  },
  'warning': {
    subtle: 'bg-orange-3 text-orange-11',
    solid: 'bg-orange-9 text-orange-contrast',
    outline: 'border-(length:--border-thick) border-orange-7 text-orange-11',
    text: 'text-orange-11',
  },
  'danger': {
    subtle: 'bg-red-3 text-red-11',
    solid: 'bg-red-9 text-red-contrast',
    outline: 'border-(length:--border-thick) border-red-7 text-red-11',
    text: 'text-red-11',
  },
  'neutral': {
    subtle: 'bg-gray-3 text-gray-11',
    solid: 'bg-gray-9 text-gray-contrast',
    outline: 'border-(length:--border-thick) border-gray-7 text-gray-11',
    text: 'text-gray-11',
  },
  'red': {
    subtle: 'bg-red-3 text-red-11',
    solid: 'bg-red-9 text-red-contrast',
    outline: 'border-(length:--border-thick) border-red-7 text-red-11',
    text: 'text-red-11',
  },
  'orange': {
    subtle: 'bg-orange-3 text-orange-11',
    solid: 'bg-orange-9 text-orange-contrast',
    outline: 'border-(length:--border-thick) border-orange-7 text-orange-11',
    text: 'text-orange-11',
  },
  'yellow': {
    subtle: 'bg-yellow-3 text-yellow-11',
    solid: 'bg-yellow-9 text-yellow-contrast',
    outline: 'border-(length:--border-thick) border-yellow-7 text-yellow-11',
    text: 'text-yellow-11',
  },
  'green': {
    subtle: 'bg-green-3 text-green-11',
    solid: 'bg-green-9 text-green-contrast',
    outline: 'border-(length:--border-thick) border-green-7 text-green-11',
    text: 'text-green-11',
  },
  'teal': {
    subtle: 'bg-teal-3 text-teal-11',
    solid: 'bg-teal-9 text-teal-contrast',
    outline: 'border-(length:--border-thick) border-teal-7 text-teal-11',
    text: 'text-teal-11',
  },
  'cyan': {
    subtle: 'bg-cyan-3 text-cyan-11',
    solid: 'bg-cyan-9 text-cyan-contrast',
    outline: 'border-(length:--border-thick) border-cyan-7 text-cyan-11',
    text: 'text-cyan-11',
  },
  'blue': {
    subtle: 'bg-blue-3 text-blue-11',
    solid: 'bg-blue-9 text-blue-contrast',
    outline: 'border-(length:--border-thick) border-blue-7 text-blue-11',
    text: 'text-blue-11',
  },
  'indigo': {
    subtle: 'bg-indigo-3 text-indigo-11',
    solid: 'bg-indigo-9 text-indigo-contrast',
    outline: 'border-(length:--border-thick) border-indigo-7 text-indigo-11',
    text: 'text-indigo-11',
  },
  'purple': {
    subtle: 'bg-purple-3 text-purple-11',
    solid: 'bg-purple-9 text-purple-contrast',
    outline: 'border-(length:--border-thick) border-purple-7 text-purple-11',
    text: 'text-purple-11',
  },
  'pink': {
    subtle: 'bg-pink-3 text-pink-11',
    solid: 'bg-pink-9 text-pink-contrast',
    outline: 'border-(length:--border-thick) border-pink-7 text-pink-11',
    text: 'text-pink-11',
  },
  'gray': {
    subtle: 'bg-gray-3 text-gray-11',
    solid: 'bg-gray-9 text-gray-contrast',
    outline: 'border-(length:--border-thick) border-gray-7 text-gray-11',
    text: 'text-gray-11',
  },
};
