// GENERATED by scripts/generators/generate-tones.ts from tokens/tones.tokens.json — do not edit.
// The vocabulary only. Rung numbers live at the call site that builds the
// class, so there is no STEP table and no table of finished class strings.
export const TONE_NAMES = ['primary', 'secondary', 'success', 'warning', 'danger', 'neutral', 'red', 'orange', 'yellow', 'green', 'teal', 'cyan', 'blue', 'indigo', 'purple', 'pink', 'gray'] as const;
export type Tone = (typeof TONE_NAMES)[number];
export const ROLE_TONES = ['primary', 'secondary', 'success', 'warning', 'danger', 'neutral'] as const;
export type RoleTone = (typeof ROLE_TONES)[number];
export const HUE_TONES = ['red', 'orange', 'yellow', 'green', 'teal', 'cyan', 'blue', 'indigo', 'purple', 'pink', 'gray'] as const;
export type HueTone = (typeof HUE_TONES)[number];
export const TONE_RAMP: Record<Tone, HueTone> = {
  'primary': 'indigo',
  'secondary': 'gray',
  'success': 'green',
  'warning': 'orange',
  'danger': 'red',
  'neutral': 'gray',
  'red': 'red',
  'orange': 'orange',
  'yellow': 'yellow',
  'green': 'green',
  'teal': 'teal',
  'cyan': 'cyan',
  'blue': 'blue',
  'indigo': 'indigo',
  'purple': 'purple',
  'pink': 'pink',
  'gray': 'gray',
};
