// GENERATED by scripts/build-tokens.mjs from src/tokens/source/tones.tokens.json — do not edit.
// Literal class strings so Tailwind can scan them; see build-tokens.mjs emitTones().
export const TONE_NAMES = ['primary', 'secondary', 'success', 'warning', 'danger', 'neutral', 'red', 'orange', 'yellow', 'green', 'teal', 'cyan', 'blue', 'indigo', 'purple', 'pink', 'gray'] as const;
export type Tone = (typeof TONE_NAMES)[number];
export const HUE_TONES = ['red', 'orange', 'yellow', 'green', 'teal', 'cyan', 'blue', 'indigo', 'purple', 'pink', 'gray'] as const;
export type HueTone = (typeof HUE_TONES)[number];
export type ToneEmphasis = 'subtle' | 'solid' | 'outline' | 'text';
export const TONES: Record<Tone, Record<ToneEmphasis, string>> = {
  'primary': {
    subtle: 'bg-accent-subtle text-accent',
    solid: 'bg-accent text-on-accent',
    outline: 'border-(length:--border-hair) border-accent text-accent',
    text: 'text-accent',
  },
  'secondary': {
    subtle: 'bg-inset text-ink-2',
    solid: 'bg-ink-2 text-app',
    outline: 'border-(length:--border-hair) border-ink-2 text-ink-2',
    text: 'text-ink-2',
  },
  'success': {
    subtle: 'bg-opt-green-subtle text-opt-green',
    solid: 'bg-opt-green text-on-opt-green',
    outline: 'border-(length:--border-hair) border-opt-green text-opt-green',
    text: 'text-opt-green',
  },
  'warning': {
    subtle: 'bg-opt-orange-subtle text-opt-orange',
    solid: 'bg-opt-orange text-on-opt-orange',
    outline: 'border-(length:--border-hair) border-opt-orange text-opt-orange',
    text: 'text-opt-orange',
  },
  'danger': {
    subtle: 'bg-danger-subtle text-danger',
    solid: 'bg-danger text-on-danger',
    outline: 'border-(length:--border-hair) border-danger text-danger',
    text: 'text-danger',
  },
  'neutral': {
    subtle: 'bg-inset text-ink-3',
    solid: 'bg-ink-3 text-app',
    outline: 'border-(length:--border-hair) border-ink-3 text-ink-3',
    text: 'text-ink-3',
  },
  'red': {
    subtle: 'bg-opt-red-subtle text-opt-red',
    solid: 'bg-opt-red text-on-opt-red',
    outline: 'border-(length:--border-hair) border-opt-red text-opt-red',
    text: 'text-opt-red',
  },
  'orange': {
    subtle: 'bg-opt-orange-subtle text-opt-orange',
    solid: 'bg-opt-orange text-on-opt-orange',
    outline: 'border-(length:--border-hair) border-opt-orange text-opt-orange',
    text: 'text-opt-orange',
  },
  'yellow': {
    subtle: 'bg-opt-yellow-subtle text-opt-yellow',
    solid: 'bg-opt-yellow text-on-opt-yellow',
    outline: 'border-(length:--border-hair) border-opt-yellow text-opt-yellow',
    text: 'text-opt-yellow',
  },
  'green': {
    subtle: 'bg-opt-green-subtle text-opt-green',
    solid: 'bg-opt-green text-on-opt-green',
    outline: 'border-(length:--border-hair) border-opt-green text-opt-green',
    text: 'text-opt-green',
  },
  'teal': {
    subtle: 'bg-opt-teal-subtle text-opt-teal',
    solid: 'bg-opt-teal text-on-opt-teal',
    outline: 'border-(length:--border-hair) border-opt-teal text-opt-teal',
    text: 'text-opt-teal',
  },
  'cyan': {
    subtle: 'bg-opt-cyan-subtle text-opt-cyan',
    solid: 'bg-opt-cyan text-on-opt-cyan',
    outline: 'border-(length:--border-hair) border-opt-cyan text-opt-cyan',
    text: 'text-opt-cyan',
  },
  'blue': {
    subtle: 'bg-opt-blue-subtle text-opt-blue',
    solid: 'bg-opt-blue text-on-opt-blue',
    outline: 'border-(length:--border-hair) border-opt-blue text-opt-blue',
    text: 'text-opt-blue',
  },
  'indigo': {
    subtle: 'bg-opt-indigo-subtle text-opt-indigo',
    solid: 'bg-opt-indigo text-on-opt-indigo',
    outline: 'border-(length:--border-hair) border-opt-indigo text-opt-indigo',
    text: 'text-opt-indigo',
  },
  'purple': {
    subtle: 'bg-opt-purple-subtle text-opt-purple',
    solid: 'bg-opt-purple text-on-opt-purple',
    outline: 'border-(length:--border-hair) border-opt-purple text-opt-purple',
    text: 'text-opt-purple',
  },
  'pink': {
    subtle: 'bg-opt-pink-subtle text-opt-pink',
    solid: 'bg-opt-pink text-on-opt-pink',
    outline: 'border-(length:--border-hair) border-opt-pink text-opt-pink',
    text: 'text-opt-pink',
  },
  'gray': {
    subtle: 'bg-opt-gray-subtle text-opt-gray',
    solid: 'bg-opt-gray text-on-opt-gray',
    outline: 'border-(length:--border-hair) border-opt-gray text-opt-gray',
    text: 'text-opt-gray',
  },
};
