// Token build entry point. Run directly:
//
//   node scripts/generators/build-tokens.ts   (via `pnpm --filter @tickets/ui tokens:build`)
//
// One generator per family, each a self-contained function returning everything
// derived from its own token file. This module holds no knowledge of any
// family: adding one is a new file plus one entry below. `border` is the one
// with no token file at all — what it emits is a utility DEFINITION, which has
// no values to read.
//
// Every generated file is written WHOLE. Nothing is spliced into hand-authored
// content — an earlier design injected regions into a shared tokens.css between
// marker comments, which meant one file was half generated and half authored
// and the only way to tell which half you were in was to find the closing
// marker.
//
// Each stylesheet is also SELF-CONTAINED, carrying its own `initial` clear above
// the values that clear applies to. That is why styles/index.css can import them
// in any order: no file can wipe another's namespace.
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { generateBorder } from './border.ts';
import { generateBreakpoints } from './breakpoints.ts';
import { generateColors } from './colors.ts';
import { generateMotion } from './motion.ts';
import { generateShadows } from './shadows.ts';
import { generateSpacing } from './spacing.ts';
import { generateTypography } from './typography.ts';
import { GENERATED_DIR, GENERATED_TS_DIR, generatedCssFile, generatedTsFile } from './utils/paths.ts';
import type { Family } from './utils/types.ts';

/** Family name -> its generator. The name is the output filename in both tiers. */
const FAMILIES: Record<string, () => Family> = {
  colors: generateColors,
  typography: generateTypography,
  border: generateBorder,
  motion: generateMotion,
  shadows: generateShadows,
  breakpoints: generateBreakpoints,
  spacing: generateSpacing,
};

const CSS_HEADER =
  '/* GENERATED by scripts/generators/build-tokens.ts — do not edit.\n' +
  '   Regenerate with `pnpm --filter @tickets/ui tokens:build`. */\n';

export function build(): void {
  mkdirSync(GENERATED_DIR, { recursive: true });
  mkdirSync(GENERATED_TS_DIR, { recursive: true });

  const write = (file: string, contents: string): void => {
    writeFileSync(file, contents, 'utf8');
    console.log(`Updated ${path.relative(process.cwd(), file)}`);
  };

  const modules: string[] = [];
  for (const [name, generate] of Object.entries(FAMILIES)) {
    const { css, ts } = generate();
    if (css) write(generatedCssFile(`${name}.css`), CSS_HEADER + css);
    // TS modules carry their own header, naming the token file each came from.
    if (ts) {
      write(generatedTsFile(`${name}.ts`), ts);
      modules.push(name);
    }
  }

  write(generatedTsFile('index.ts'), barrel(modules));
}

/**
 * Barrel over the generated modules. Regenerated so it cannot go stale.
 *
 * Over the families that PRODUCED one, not every family — `border` emits CSS
 * alone, and a barrel built from the family list would re-export a module that
 * was never written.
 */
function barrel(names: string[]): string {
  return (
    '// GENERATED by scripts/generators/build-tokens.ts — do not edit.\n' +
    names
      .slice()
      .sort()
      .map((n) => `export * from './${n}';\n`)
      .join('')
  );
}

// Importing this module must not write files.
const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  build();
}
