// Token build entry point. Run directly:
//
//   node scripts/generators/build-tokens.ts    (via `pnpm --filter @tickets/ui tokens:build`)
//
// Writes one WHOLE file per token type into `styles/generated/`, plus the tone
// vocabulary as TypeScript. Nothing is spliced into hand-authored content: an
// earlier design injected regions into a shared tokens.css between marker
// comments, which meant one file was half generated and half authored and the
// only way to tell which half you were in was to find the closing marker.
//
// Every generated file is SELF-CONTAINED — each carries its own `initial` clear
// above the values that clear applies to. That is why index.css can import them
// in any order. An earlier split had the clears in a separate authored file and
// needed the import order to be exactly right or the colours were wiped.
//
// Two of the token files are read but emit nothing, by design: layout.tokens.json
// and motion's `duration`. `border-2` is 2px and `duration-200` is 200ms because
// the Tailwind class says so; emitting a token would create the second copy of
// the value that is the only way the two could ever disagree. Those files record
// which rungs are sanctioned, and `foundation/spec.ts` reads them for the gallery.
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { emitThemedCss } from './emit-themed-css.ts';
import { generateMotion } from './generate-motion.ts';
import { generateRadius } from './generate-radius.ts';
import { generateTones } from './generate-tones.ts';
import { generateTypography } from './generate-typography.ts';
import { resolveTokenMaps } from './resolve-token-maps.ts';
import { colorVarLines } from './utils/color-var-lines.ts';
import { shadowVarLines } from './utils/shadow-var-lines.ts';
import { GENERATED_DIR, GENERATED_TS_DIR, generatedCssFile, generatedTsFile } from './utils/paths.ts';
import type { TokenMap } from './utils/types.ts';

const HEADER =
  '/* GENERATED by scripts/generators/build-tokens.ts — do not edit.\n' +
  '   Regenerate with `pnpm --filter @tickets/ui tokens:build`. */\n';

const pick = (map: TokenMap, kind: 'color' | 'shadow'): TokenMap =>
  Object.fromEntries(Object.entries(map).filter(([, token]) => token.type === kind));

/** Every generated stylesheet, keyed by the file it is written to. */
function emitStylesheets(): Record<string, string> {
  const { light, dark } = resolveTokenMaps();

  return {
    // Surfaces and literals ride along with the ramps rather than getting their
    // own files: all three occupy the `--color-*` namespace, so they must sit
    // behind one `--color-*: initial`. Splitting them would reintroduce exactly
    // the cross-file ordering constraint this layout removes.
    'colors.css': emitThemedCss({
      light: pick(light, 'color'),
      dark: pick(dark, 'color'),
      bridge: colorVarLines,
      clear: '--color-*: initial;',
    }),
    'shadows.css': emitThemedCss({
      light: pick(light, 'shadow'),
      dark: pick(dark, 'shadow'),
      bridge: shadowVarLines,
    }),
    'typography.css': generateTypography(),
    'radius.css': generateRadius(),
    'motion.css': generateMotion(),
  };
}

/** Every generated TypeScript module, keyed by the file it is written to. */
function emitModules(): Record<string, string> {
  const { light } = resolveTokenMaps();
  return { 'tones.ts': generateTones(light) };
}

export function build(): void {
  mkdirSync(GENERATED_DIR, { recursive: true });
  mkdirSync(GENERATED_TS_DIR, { recursive: true });

  const write = (file: string, contents: string): void => {
    writeFileSync(file, contents, 'utf8');
    console.log(`Updated ${path.relative(process.cwd(), file)}`);
  };

  for (const [name, css] of Object.entries(emitStylesheets())) {
    write(generatedCssFile(name), HEADER + css);
  }
  // The TS modules carry their own header — each states which token file it came
  // from, which differs per module and would be wrong as one shared string.
  for (const [name, ts] of Object.entries(emitModules())) {
    write(generatedTsFile(name), ts);
  }
}

// Importing this module must not write files.
const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  build();
}
