import { readTokenFile } from './utils/read-token-file.ts';
import type { ColorDoc, SemanticDoc, TokenMap } from './utils/types.ts';

/**
 * Emit `src/style/tones/tones.generated.ts` — the tone vocabulary.
 *
 * The vocabulary ONLY. Rung numbers live at the call site that builds the
 * class, so there is no STEP table and no table of finished class strings.
 * An earlier design emitted both; it meant three places could disagree about
 * what `subtle` was.
 *
 * The hue list is DERIVED from the colour ramps rather than declared. It used
 * to live in its own `tones.tokens.json`, which made it a second copy of the
 * ramp names that could disagree with the ramps themselves — a hue listed but
 * unpainted, or painted but unlisted, and nothing to say which was intended.
 * The ramps are the only place a hue can actually exist, so they are the list.
 * Ramp ORDER is therefore key order in `colors.*.tokens.json`; gray sits last
 * there because the neutral reads after the chromatics.
 */
export function generateTones(light: TokenMap): string {
  const colors = readTokenFile<ColorDoc>('colors.light.tokens.json');
  const roles = readTokenFile<SemanticDoc>('semantic.tokens.json').scale;
  const hues = Object.keys(colors);

  assertRampsAreUniform(colors);

  // A tone is a NAME for a ramp. Roles come first so `primary` reads before
  // `red`, then the hues — matching TONE_NAMES' declaration order.
  const rampOf: Record<string, string> = { ...roles };
  for (const hue of hues) rampOf[hue] = hue;
  const ordered = [...Object.keys(roles), ...hues];

  assertRolesResolve(roles, light);

  const quoted = (values: string[]): string => values.map((v) => `'${v}'`).join(', ');
  // A tone name is not always a ramp name (`primary` paints from `indigo`), so
  // every component building a class string needs this mapping — it is the one
  // thing that keeps `tone="danger"` from having to be spelled `tone="red"` at
  // sixty call sites. Named TONE_RAMP for what it RETURNS: a ramp name, which
  // goes straight into `bg-${…}-9`. Under its old name, TONE_SCALE, every
  // consumer had to disclaim that in a comment.
  const rampEntries = ordered.map((n) => `  '${n}': '${rampOf[n]}',`).join('\n');

  return (
    `// GENERATED by scripts/generators/generate-tones.ts from tokens/colors.light.tokens.json — do not edit.\n` +
    `// The vocabulary only. Rung numbers live at the call site that builds the\n` +
    `// class, so there is no STEP table and no table of finished class strings.\n` +
    `export const TONE_NAMES = [${quoted(ordered)}] as const;\n` +
    `export type Tone = (typeof TONE_NAMES)[number];\n` +
    `export const ROLE_TONES = [${quoted(Object.keys(roles))}] as const;\n` +
    `export type RoleTone = (typeof ROLE_TONES)[number];\n` +
    `export const HUE_TONES = [${quoted(hues)}] as const;\n` +
    `export type HueTone = (typeof HUE_TONES)[number];\n` +
    `export const TONE_RAMP: Record<Tone, HueTone> = {\n` +
    rampEntries +
    `\n};\n`
  );
}

/**
 * Every ramp carries the same rungs.
 *
 * Replaces the old `steps`/`emphasis` walk, which asked the narrower question
 * "does every rung a treatment reaches for exist everywhere" and needed a whole
 * token file to state which rungs those were. Since a component now spells its
 * own rung, ANY rung is reachable, so the useful invariant is simply that the
 * ramps agree with each other. A ramp missing step 3 makes `bg-teal-3` a class
 * with no colour behind it — invisible unless someone looks at that exact tone.
 */
function assertRampsAreUniform(colors: ColorDoc): void {
  const entries = Object.entries(colors);
  const [firstName, firstRamp] = entries[0] ?? [];
  if (!firstName || !firstRamp) throw new Error('colors.light.tokens.json defines no ramps');
  const expected = Object.keys(firstRamp);

  for (const [name, ramp] of entries) {
    const steps = Object.keys(ramp);
    const missing = expected.filter((s) => !steps.includes(s));
    const extra = steps.filter((s) => !expected.includes(s));
    if (missing.length > 0 || extra.length > 0) {
      throw new Error(
        `ramp "${name}" does not match "${firstName}": ` +
          [
            missing.length ? `missing ${missing.join(', ')}` : '',
            extra.length ? `unexpected ${extra.join(', ')}` : '',
          ]
            .filter(Boolean)
            .join('; '),
      );
    }
  }
}

/**
 * Every role points at a ramp that exists and is painted.
 *
 * The role map is the one indirection left — `danger` names a JOB, and
 * semantic.tokens.json says which ramp currently does it. A role pointing
 * somewhere unpainted would build `bg-crimson-9`, a class with no colour.
 */
function assertRolesResolve(roles: Record<string, string>, light: TokenMap): void {
  for (const [role, ramp] of Object.entries(roles)) {
    if (!(`${ramp}-9` in light)) {
      throw new Error(`role "${role}" resolves to ramp "${ramp}", which the colours do not define`);
    }
  }
}
