import { readTokenFile, withoutMeta } from './utils/read-token-file.ts';
import type { SemanticDoc, TokenMap, TonesDoc } from './utils/types.ts';

/**
 * Emit `src/style/tones/tones.generated.ts` — the tone vocabulary.
 *
 * The vocabulary ONLY. Rung numbers live at the call site that builds the
 * class, so there is no STEP table and no table of finished class strings.
 * An earlier design emitted both; it meant three places could disagree about
 * what `subtle` was.
 *
 * The `steps` / `emphasis` maps in tones.tokens.json are still read, but
 * nothing is emitted from them. They are walked as a build-time assertion:
 * every rung a treatment reaches for has to exist on every ramp, or
 * `bg-teal-3` is a class with no colour behind it.
 */
export function generateTones(light: TokenMap): string {
  const doc = readTokenFile<TonesDoc>('tones.tokens.json');
  const roles = readTokenFile<SemanticDoc>('semantic.tokens.json').scale;

  // `emphasis` names rungs rather than numbering them, so resolve one level
  // before building anything. A typo in a step name would otherwise sail
  // through as `undefined` and produce `bg-red-undefined`.
  const steps = withoutMeta(doc.steps);
  const rung = (name: string): number | string => {
    const step = steps[name];
    if (step === undefined) {
      throw new Error(`emphasis references step "${name}", which tones.tokens.json does not define`);
    }
    return step;
  };
  const emphasis = Object.fromEntries(
    Object.entries(withoutMeta(doc.emphasis)).map(([name, jobs]) => [
      name,
      Object.fromEntries(Object.entries(jobs).map(([job, step]) => [job, rung(step)])),
    ]),
  ) as Record<string, Record<string, number | string>>;

  // A tone is a NAME for a ramp. Roles come first so `primary` reads before
  // `red`, then the hues — matching TONE_NAMES' declaration order.
  const rampOf: Record<string, string> = { ...roles };
  for (const hue of doc.hues) rampOf[hue] = hue;
  const ordered = [...Object.keys(roles), ...doc.hues];

  assertRampsCoverEmphasis(ordered, rampOf, emphasis, light);

  const quoted = (values: string[]): string => values.map((v) => `'${v}'`).join(', ');
  // A tone name is not always a ramp name (`primary` paints from `indigo`), so
  // every component building a class string needs this mapping — it is the one
  // thing that keeps `tone="danger"` from having to be spelled `tone="red"` at
  // sixty call sites. Named TONE_RAMP for what it RETURNS: a ramp name, which
  // goes straight into `bg-${…}-9`. Under its old name, TONE_SCALE, every
  // consumer had to disclaim that in a comment.
  const rampEntries = ordered.map((n) => `  '${n}': '${rampOf[n]}',`).join('\n');

  return (
    `// GENERATED by scripts/generators/generate-tones.ts from tokens/tones.tokens.json — do not edit.\n` +
    `// The vocabulary only. Rung numbers live at the call site that builds the\n` +
    `// class, so there is no STEP table and no table of finished class strings.\n` +
    `export const TONE_NAMES = [${quoted(ordered)}] as const;\n` +
    `export type Tone = (typeof TONE_NAMES)[number];\n` +
    `export const ROLE_TONES = [${quoted(Object.keys(roles))}] as const;\n` +
    `export type RoleTone = (typeof ROLE_TONES)[number];\n` +
    `export const HUE_TONES = [${quoted(doc.hues)}] as const;\n` +
    `export type HueTone = (typeof HUE_TONES)[number];\n` +
    `export const TONE_RAMP: Record<Tone, HueTone> = {\n` +
    rampEntries +
    `\n};\n`
  );
}

/**
 * Every rung any treatment reaches for must exist on every ramp.
 *
 * This is the check that makes the unemitted `steps`/`emphasis` maps worth
 * keeping: it is about the RAMPS, not about the class strings. A ramp missing
 * step 3 would render `bg-teal-3` as no background at all — visible only to
 * someone looking at that exact tone in that exact treatment.
 */
function assertRampsCoverEmphasis(
  ordered: string[],
  rampOf: Record<string, string>,
  emphasis: Record<string, Record<string, number | string>>,
  light: TokenMap,
): void {
  const reached = new Set<number | string>();
  for (const jobs of Object.values(emphasis)) {
    for (const step of Object.values(jobs)) reached.add(step);
  }

  for (const name of ordered) {
    const ramp = rampOf[name];
    for (const step of reached) {
      const token = `${ramp}-${step}`;
      if (!(token in light)) {
        throw new Error(`tone "${name}" needs ${token}, which the ramps do not define`);
      }
    }
  }
}
